spring:
  application:
    name: gateway

zuul:
  routes:
    accounts-api:
      path: /accounts-service/**
      serviceId: accounts-service

    transactions-api:
      path: /transactions-service/**
      serviceId: transactions-service

    customers-api:
      path: /customers-service/**
      serviceId: customers-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/




